### ISSUE TITLE
Dependencies that usually are dev deps are problematic.

### ISSUE THREAD

**Issue by pkucmus** [mirumee/ariadne-codegen#103]
Usually one has the likes of `isort`, and `black` in dev dependencies with close to little care which versions those are on. Codegen having those in main deps enforce specific versions of these. If those are used to post-process the generated code - which would make them truly main deps then maybe that post-process feature should be a plugin? At the very least I propose unlocking the post-processors to a `"*"` version. 
This is safe as I can't imagine you relly on the output of the linters/formaters, right?

**Comment by rafalp** [comment]
We actually run those on generated code as final step ☠️
