### ISSUE TITLE
Custom scalar 'parse' function is applied directly to a List[<scalar>], instead of being mapped to each item in list

### ISSUE THREAD

**Issue by james-seymour-cubiko** [mirumee/ariadne-codegen#104]
hey! another potential bug / opportunity for improvement here - I currently have a custom scalar called `Time` that I would like to deserialise from a string into a `pendulum.time.Time` instance. 

However, the actual return value of the `times` query is a **list** of `Time` instances, not just a single `Time` instance - in this case, I would expect the custom scalar parser function `time_utils.parse_time` to be applied to each element of the `times` array, rather than having the whole array passed into the function once.

**schema.graphql**
```
scalar Time

type Query {
    times: [Time!]!
}
```

**time_utils.py**
```
from pendulum.time import Time
from pendulum.parser import parse

def parse_time(time: str) -> Time:
    return parse(time).time()
```

**pyproject.yaml**
```
[tool.ariadne-codegen]
...
files_to_include = ["time_utils.py"]

[tool.ariadne-codegen.scalars.Time]
type = "Time"
parse = "parse_time"
import = ".time_utils"
```

Happy to submit a PR for this - I'm thinking the `BaseModel.decode_custom_scalars` function could instead be generated as something like:
```
    @validator("*", pre=True)
    def decode_custom_scalars(cls, value: Any, field: ModelField) -> Any:
        decode = SCALARS_PARSE_FUNCTIONS.get(field.type_)
        if decode is None or not callable(decode):
            return value

        if isinstance(value, list):
            return [decode(item) for item in value]

        return decode(value)
```

As a side note, as much as I prefer the `from ... import ...` syntax, for ease of use I would imagine that specifying custom scalar parsing in `pyproject.yaml` in the following way would be nicer,
```
[tool.ariadne-codegen.scalars.Time]
type = "pendulum.time.Time"
parse = ".time_utils.parse_time"
serialize = "str"
```
since the one `time_utils.py` module isn't responsible for exporting all of the types / functions required (including builtins like `str`). Definitely happy to hear why the current way is better though!

**Comment by rafalp** [comment]
I'm okay with the change.
