### ISSUE TITLE
Differentiate between null and unset values.

### ISSUE THREAD

**Issue by strue36** [mirumee/ariadne-codegen#121]
As discussed in #116

The issue I'm having is that I have a lot of optional arguments and optional fields within them.
The current generated code sets every missing value to `None`, and then sends `"field": null`.

Our GraphQL server interprets missing arguments/fields as semantically different to null values and therefore I want to remove them from the json. I spent some time today wondering if this is actually a bug in our server/the framework we are using, but the [GraphQL language spec](http://spec.graphql.org/June2018/#sec-Null-Value) makes it clear that they are semantically different.

I had assumed that `None` representing a missing optional argument would be far more common than explicitly sending `null`, and that removing any null entry would result in payloads that are closer to what a user intended (and therefore should be the default behaviour). That might not be the case and if so we can raise an issue for null handling in general and discuss there. I have a similar fix in `base_model.py` for stripping nulls which would raise the same discussion points.

> I'm not a fan of choosing one of these options. I wonder if it is a way to distinguish the default `None` from user-provided `None`. Maybe we should use something different for optional arguments and input fields, (`graphql.Undefined`?) and then remove only this from the payload. @rafalp What do you think?

_Originally posted by @mat-sop in https://github.com/mirumee/ariadne-codegen/issues/116#issuecomment-1494145149_

[This discussion from openapi-python-client](https://github.com/openapi-generators/openapi-python-client/discussions/385#discussioncomment-601623) explains their "Unset" concept, however that references [some Pydantic features](https://docs.pydantic.dev/usage/exporting_models/#modeldict) that may save a lot of trouble here.

We need to handle nullability at the GraphQL argument level and within an input type.

**Comment by strue36** [comment]
Based on a quick test, the Pydantic flag `exclude_unset=True` will behave as required within the input types, but we still need to handle this at the top level (missing arguments).

**Comment by mat-sop** [comment]
As discussed [here](https://github.com/mirumee/ariadne-codegen/pull/116) I will use `exclude_unset` for inputs and change the default value of optional arguments to something different than `None` to filter this value out from the payload.
