### ISSUE TITLE
Failures with Dgraph generated GraphQL schema

### ISSUE THREAD

**Issue by nargetdev** [mirumee/ariadne-codegen#131]
I'm going to just post my "sanitized" schema here for reference to what's failing.  To the best of my knowledge it's top level lists - I saw a post claiming to fix this but I tried pulling new ver and it seems I'm still crashing on those `types` and `inputs`

So here's the sanitized schema - the schema as generated from Dgraph's backend, and then ariadne-problematic bits commented out.

[SANITIZED.schema.graphql.txt](https://github.com/mirumee/ariadne-codegen/files/11224988/SANITIZED.schema.graphql.txt)

... and here's the target schema (unsanitized - the raw output of Dgraph generated schema, which breaks ariadne-codegen currently)

[schema.graphql.txt](https://github.com/mirumee/ariadne-codegen/files/11224999/schema.graphql.txt)

[queries.graphql.txt](https://github.com/mirumee/ariadne-codegen/files/11225008/queries.graphql.txt)

Cheers, and happy bunting.
I'll put in some effort here too, if I can get this test case to pass I'll open a PR

P.S. Here's a oneliner to get that schema from the `.../admin` GraphQL endpoint using `fish`:

```fish
echo -en (curl 'http://127.0.0.1:8080/admin' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: file://' --data-binary '{"query":"{\n  getGQLSchema {\n    generatedSchema\n  }\n}"}' --compressed|jq .data.getGQLSchema.generatedSchema|sed -e 's/^"//' -e 's/"$//')|sed 's/\\\"/\"/g'
```

**Comment by rafalp** [comment]
Can you put that failing schema on github gist? We don't need it all in the issue.

**Comment by nargetdev** [comment]
yes one sec

**Comment by rafalp** [comment]
Actually it would be perfect if all those code blocks were instead gists with descriptions what they are.

**Comment by mat-sop** [comment]
@nargetdev I found what causes problem with your schema. `in`, `and`, `or`, `not` are keywords in python, so following code is not valid:
```py
class IntFilter(BaseModel):
    ...
    in: Optional[List[Optional[Int]]]
    ...
```

This issue is already [fixed](https://github.com/mirumee/ariadne-codegen/issues/108) on main and it will be included in next release. With this fix, example from above will look like this:
```py
class IntFilter(BaseModel):
    ...
    in_: Optional[List[Optional[int]]] = Field(alias="in")
    ...
```

**Comment by mat-sop** [comment]
@nargetdev Fix for this problem has just been released, so I'm closing this issue.
