### ISSUE TITLE
Generate mixins for fragments

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne-codegen#135]
When writing business logic its useful to have limited number of type representations to deal with.

For example, ORMs usually default to single representation of an object stored in database, and developers then write business logic around this representation.

GraphQL also have solution for unifying those representations across the client, in form of fragments:

```grapqhl
query GetCustomer($id: ID!) {
  customer(id: $id): {
    ... CustomerData
  }
}

query GetCustomers($first: Int, $last: Int, $before: ID, $after: ID) {
  customers(first: $first, last: $last, before: $before, after: $after): {
    edges {
      cursor
      node {
        ...CustomerData
      }
    }
  }
}

fragment CustomerData on Customer {
  id
  firstName
  lastName
  companyName
  email
  trustScore
}
```

If customers returned from `get_customer` and `get_customers` methods in generated client both implemented `CustomerData`, then rest of business logic dealing with customers in my service could use this `CustomerData` as a type:

```python
async def notify_customer(customer: CustomerData):
    # customer is guaranteed to have an ID and email address


async def make_checkout(customer: CustomerData):
    # customer is guaranteed to have an ID, email address and trust_score I need in checkout logic
```

**Comment by markedwards** [comment]
This is really critical, thanks for putting it on the roadmap.
