### ISSUE TITLE
Response field type codegen can generate classes without bodies

### ISSUE THREAD

**Issue by krashanoff** [mirumee/ariadne-codegen#140]
Hi there. I think this is a great addition to the Ariadne family of tooling, and used it today to much success. I did run into a bug, however. I cannot share the schema used to reproduce this issue as it's for a closed-source project, but I do have a solution that I will open a PR with later today. The solution is pretty hacky, though, so I was curious if any maintainers have encountered the issue prior.

I encountered a situation where, when generating a client from a provided schema and collection of queries + fragments, there was an edge case where one of the generated response field types was an empty class without any members. The type still inherited from `BaseModel`, but was missing its body. Once the body was added, the client would work fine. The solution I mentioned was injecting an AST transformation to fill said empty bodies with a `pass` statement in `utils.py`'s `ast_to_str`.

**Comment by mat-sop** [comment]
Hi, I'm working on #135 which will change how fragments are handled and it will also take care of cases where a generated class has no body.
But I wasn't aware that this could occur before this change, could you provide an example schema and query (not from your project) that currently produces a class without a body?

**Comment by krashanoff** [comment]
I will try to find the minimum subset of the schema that produces the problem tonight. This said, I'm confident that #143 fixes the problem.

**Comment by mat-sop** [comment]
@krashanoff Do you have query similar as in #142 ? This can produce class without body. For example:
```gql
query TestQuery {
    testQuery {
        ...TestFragment
    }
}

fragment TestFragment on TestInterface {
    ... on SubTypeA {
      fieldA
    }
    ... on SubTypeB {
      fieldB
    }
}
```
