### ISSUE TITLE
Union types always gets parsed as the interface

### ISSUE THREAD

**Issue by bombsimon** [mirumee/ariadne-codegen#145]
Generated unions of interfaces always gets parsed to the interface itself since the interface is added first. This is reproducible with the test/example in [`inline_fragments`](https://github.com/mirumee/ariadne-codegen/blob/1edb477ae544d4fc825b28cc7c911f36eaeab773/tests/main/clients/inline_fragments/expected_client/interface_a.py) and `InterfaceA`.

```python
class InterfaceA(BaseModel):
    query_i: Union[
        "InterfaceAQueryIInterface",
        "InterfaceAQueryITypeA",
        "InterfaceAQueryITypeB",
    ] = Field(alias="queryI")


class InterfaceAQueryIInterface(BaseModel):
    __typename__: str = Field(alias="__typename")
    id: str


class InterfaceAQueryITypeA(BaseModel):
    __typename__: str = Field(alias="__typename")
    id: str
    field_a: str = Field(alias="fieldA")


class InterfaceAQueryITypeB(BaseModel):
    __typename__: str = Field(alias="__typename")
    id: str
    field_b: str = Field(alias="fieldB")


InterfaceA.update_forward_refs()
InterfaceAQueryIInterface.update_forward_refs()
InterfaceAQueryITypeA.update_forward_refs()
InterfaceAQueryITypeB.update_forward_refs()


def main():
    d = {
        "queryI": {
            "__typename": "InterfaceAQueryITypeB",
            "id": "i1",
            "fieldB": "I'm field b",
        }
    }

    o = InterfaceA.parse_obj(d)
    print_object(o)


def print_object(obj):
    print(type(obj.query_i))
    for k, v in obj.query_i.__dict__.items():
        print(f"k={k} v={v}")
```

Will output

```sh
<class '__main__.InterfaceAQueryIInterface'>
k=id v=i1
```

The reason seems to be because `Pydantic` always parses this from top to bottom and uses the first one that match, see [documentation here](https://docs.pydantic.dev/latest/usage/types/#unions). Since `InterfaceAQueryIInterface` only contains `id` and so does or object it will match.

Moving the interface to the bottom like this:
```python
class InterfaceA(BaseModel):
    query_i: Union[
        "InterfaceAQueryITypeA",
        "InterfaceAQueryITypeB",
        "InterfaceAQueryIInterface", # <- Interface now last
    ] = Field(alias="queryI")
```

Will output

```sh
<class '__main__.InterfaceAQueryITypeB'>
k=id v=i1
k=field_b v=I'm field b
```

The Pydantic documentation also mentions [Smart Union](https://docs.pydantic.dev/latest/usage/model_config/#smart-union) which supposedly should be configured like this:

```python
class InterfaceA(BaseModel):
    query_i: Union[
        "InterfaceAQueryIInterface", "InterfaceAQueryITypeA", "InterfaceAQueryITypeB"
    ] = Field(alias="queryI")

    class Config:
        smart_union = True
```

But doing so does not result in properly interpreted unions in this example so I guess I'm missing something here.

Also this will only work if two interfaces doesn't share the same fields, f.ex. in the following case:

```graphql
interface InterfaceAQueryIInterface {
    id: String!
}

type InterfaceAQueryITypeA implements InterfaceAQueryIInterface {
    id: String!
    field: String!
}

type InterfaceAQueryITypeB implements InterfaceAQueryIInterface {
    id: String!
    field: String!
}
```

We would always get back the interface listed first in the union. I'm not sure what the optimal way for this would be, one easy way would be to just add a dummy field for the types but there's also possible to [parse data into a specific type](https://lyz-code.github.io/blue-book/coding/python/pydantic/?h=parse_obj_as#parsing-data-into-a-specified-type) which could be done if we read the type from `__typename`. However that could be quite messy since it would have to be done recursively rather than just parsing the response into `InterfaceA`.

**Comment by mat-sop** [comment]
Hey, I looked into this issue and it looks like pydantic's [discriminated unions](https://docs.pydantic.dev/latest/usage/types/#discriminated-unions-aka-tagged-unions) might solve this. Basing on the same example we would get:
```py
class InterfaceA(BaseModel):
    query_i: Union[
        "InterfaceAQueryIInterface",
        "InterfaceAQueryITypeA",
        "InterfaceAQueryITypeB",
    ] = Field(alias="queryI", discriminator="typename__")


class InterfaceAQueryIInterface(BaseModel):
    typename__: Literal["Interface", "TypeC"] = Field(alias="__typename") # we need to list all types which don't have model for them
    id: str


class InterfaceAQueryITypeA(BaseModel):
    typename__: Literal["TypeA"] = Field(alias="__typename")
    id: str
    field_a: str = Field(alias="fieldA")


class InterfaceAQueryITypeB(BaseModel):
    typename__: Literal["TypeB"] = Field(alias="__typename")
    id: str
    field_b: str = Field(alias="fieldB")


InterfaceA.update_forward_refs()
InterfaceAQueryIInterface.update_forward_refs()
InterfaceAQueryITypeA.update_forward_refs()
InterfaceAQueryITypeB.update_forward_refs()
```
This assumes that in the schema there are 3 types that implement `Interface` - `TypeA`, `TypeB`, and `TypeC`, but in query, we only select specific fields for 2 of them - `TypeA` and `TypeB`. Then all 3 classes are correctly mapped:
```py
objects_data = [
    {
        "queryI": {
            "__typename": "TypeA",
            "id": "id1",
            "fieldA": "AAA",
        }
    },
    {
        "queryI": {
            "__typename": "TypeB",
            "id": "id2",
            "fieldB": "BBB",
        }
    },
    {
        "queryI": {
            "__typename": "TypeC",
            "id": "id3",
        }
    },
]

for data in objects_data:
    obj = InterfaceA.parse_obj(data)
    print(type(obj.query_i))
    print(obj.query_i)
```
```bash
<class '__main__.InterfaceAQueryITypeA'>
typename__='TypeA' id='id1' field_a='AAA'
<class '__main__.InterfaceAQueryITypeB'>
typename__='TypeB' id='id2' field_b='BBB'
<class '__main__.InterfaceAQueryIInterface'>
typename__='TypeC' id='id3'
```

**Comment by bombsimon** [comment]
Cool, thanks!

I took a stab at this but not sure if it's the right approach. Given that `__typename` will always be a custom object type, this could not be a simple type like `String!` or `Int!`?

If so, we could change this:
https://github.com/mirumee/ariadne-codegen/blob/0644ed645fbd04b0ea758402126037e75efd3b5a/ariadne_codegen/client_generators/result_types.py#L318-L321

To

```python
return GraphQLField(type_=GraphQLScalarType(name=type_name))
```

And then in `parse_operation_field_type` in https://github.com/mirumee/ariadne-codegen/blob/0644ed645fbd04b0ea758402126037e75efd3b5a/ariadne_codegen/client_generators/result_fields.py#L57

We could add:

```python
if field.name.value == TYPENAME_FIELD_NAME:
    return (
        generate_subscript(
            value=generate_name("Literal"),
            slice_=generate_constant(value=type_.name),
        ),
        [],
    )
```

This will make the generated code in `inline_fragments/interface_a.py` look like this:

```python
class InterfaceA(BaseModel):
    query_i: Union[
        "InterfaceAQueryIInterface", "InterfaceAQueryITypeA", "InterfaceAQueryITypeB"
    ] = Field(alias="queryI")


class InterfaceAQueryIInterface(BaseModel):
    typename__: Literal["Interface"] = Field(alias="__typename")
    id: str


class InterfaceAQueryITypeA(BaseModel):
    typename__: Literal["TypeA"] = Field(alias="__typename")
    id: str
    field_a: str = Field(alias="fieldA")


class InterfaceAQueryITypeB(BaseModel):
    typename__: Literal["TypeB"] = Field(alias="__typename")
    id: str
    field_b: str = Field(alias="fieldB")
```

Is this a reasonable patch or is it too naïve?

**Comment by mat-sop** [comment]
Not sure why should we change to `return GraphQLField(type_=GraphQLScalarType(name=type_name))`. What is `type_name`? This `GraphQLField(type_=GraphQLNonNull(type_=GraphQLScalarType(name="String")))` already represents `String!`.

In my previous example I assumed that [schema](https://github.com/mirumee/ariadne-codegen/blob/1edb477ae544d4fc825b28cc7c911f36eaeab773/tests/main/clients/inline_fragments/schema.graphql) has additional type, eg. 
```gql
type TypeC implements Interface {
  id: ID!
  fieldC: Float!
}
```
I wanted to show that sometimes we don't have separate model for every type, in query we only specified `TypeA` and `TypeB` so we generated models only for them + general one for interface. In order to `discriminator` to work we need to list all possible types, that's why I added `TypeC` to annotation `Literal["Interface", "TypeC"]`, even though we don't have model for `TypeC` (`"Interface"` in this case is redundant but there is no harm in leaving it, depends on implementation).

I only considered generated result so far, I didn't think of implementation yet, but looking at example of generated code you provided I can tell it may be too naive. There is no `discriminator` argument in `query_i: ... = Field(alias="queryI")` , so how it solves discussed issues? Also keep in mind that usage of discrimator may vary for [nested](https://docs.pydantic.dev/latest/usage/types/#nested-discriminated-unions) and [regular annotations](https://docs.pydantic.dev/latest/usage/types/#discriminated-unions-aka-tagged-unions).
Also I'm not sure if we should change annotation of `typename__` if then there is no union, maybe someone just added it to query? If we do we need to list all possible types under `Literal`.

**Comment by bombsimon** [comment]
> Not sure why should we change to return GraphQLField(type_=GraphQLScalarType(name=type_name)). What is type_name?

That's the type of the interface we're generating, so `TypeA`, `TypeB` etc.

> I wanted to show that sometimes we don't have separate model for every type

Ah, makes sense. And yeah, that will for sure be a problem with my approach.

> Also I'm not sure if we should change annotation of typename__ if then there is no union, maybe someone just added it to query?

Yeah I was thinking about that as well but also thought that if we know the type it will contain it wouldn't harm. But yeah, mostly just because I wanted a minimal example, should probably not do that.

I'll hold off any work on this for now. I wrote a plugin that sorts the interface type last which solves most of the cases for me, although it still fails for implementations with the exact same names.
