### ISSUE TITLE
Feature request: set `default=None` on optional input type fields

### ISSUE THREAD

**Issue by acarapetis** [mirumee/ariadne-codegen#165]
Consider the input type

```graphql
input User {
    username: String!
    fullName: String
}
```

for which `ariadne-codegen` generates an input model looking something like:

```python
class User(BaseModel):
    username: str
    full_name: Optional[str] = Field(alias="fullName")
```

If we try to instantiate this model using only a username, pyright complains:

```python
u = User(username="jen") # Argument missing for parameter "fullName"
```

Note that this code does work fine at runtime - unfortunately pydantic uses a slightly different convention to standard python dataclasses and defaults optional fields to None automatically, but pyright treats it as a dataclass-like type and thus expects all fields without defaults to be passed explicitly.

When I'm writing my own pydantic schemas, I always add an explicit `= None` to optional fields to avoid these false positives - would there be any issue with modifying ariadne-codegen to include this when appropriate?

**Comment by mat-sop** [comment]
Hey, I looked into this, and it looks like this change won't cause any issues. I was concerned about behaviour of `exclude_unset` used in our base clients, but I did small [test](https://gist.github.com/mat-sop/65c6456fffb5bdfb5b67c308e53c18f3) and adding `= None` didn't make a difference.

Tbh I think that this is something that should be handled by pyright or pydantic, as we don't generate "unusual" models. If it's not possible to solve there, I would suggest creating a plugin to codegen. You can use [`generate_input_field`](https://github.com/mirumee/ariadne-codegen/blob/main/PLUGINS.md#generate_input_field) hook to easily alter default values of input fields, eg. 

 ```py
 import ast

from ariadne_codegen import Plugin
from graphql import GraphQLInputField


class DefaultValuesPlugin(Plugin):
    def generate_input_field(
        self,
        field_implementation: ast.AnnAssign,
        input_field: GraphQLInputField,
        field_name: str,
    ) -> ast.AnnAssign:
        if not is_optional(field_implementation):
            return field_implementation
        
        # Cases to handle:
        # 1. there is no field_implementation.value
        # 2. field_implementation.value represents Field(...)
        #   2.1. there is `default=` keyword in Field(...)
        #   2.2. Field(...) doesn't have `default` keyword 
        # 3. default value is already assigned

def is_optional(field_implementation: ast.AnnAssign) -> bool:
    ...

 ```

**Comment by acarapetis** [comment]
@mat-sop Thanks for looking into it! I agree that it's not really your problem. Unfortunately I don't think it's going to be solved in either pydantic (v1) or pyright  - it's a breaking change in pydantic to change the semantics to match dataclasses, and pyright's philosophy is to avoid "mypy-plugin" style custom support for individual libraries, so the pydantic constructor type inference is only available via claiming to be a dataclass.

Pydantic v2 ([seemingly coming quite soon](https://github.com/pydantic/pydantic/issues/5919)) is going to make the breaking change: [`Optional` semantics will match dataclasses](https://docs.pydantic.dev/latest/blog/pydantic-v2/#required-vs-nullable-cleanup)! Thus I think you'll probably want to make this change for compatibility with v2 anyway?

**Comment by mat-sop** [comment]
Let's wait for pydantic v2 actual release, to not modify our code basing on api that still might change. You're right, if this change with `Optional` semantics gonna be included then we will need to make this change anyway.

**Comment by acarapetis** [comment]
Fair enough. Thanks 🙂

**Comment by acarapetis** [comment]
FYI pydantic v2 [has been released](https://pypi.org/project/pydantic/#history), and the change to required/optional semantics [has gone through](https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields).
