### ISSUE TITLE
Support @mixin directive on fragments

### ISSUE THREAD

**Issue by markedwards** [mirumee/ariadne-codegen#174]
It would be useful to be able to include a mixin class on a generated fragment type, so it isn't necessary to add the directive redundantly in all of the fields that include that fragment.

Something like:

```GraphQL
fragment FooFields on Foo @mixin(from: ".mixins", import: "Bar") {
  ...
}

query {
  foo {
    ...FooFields
  }
}
```

ending up with:

```Python
class Foo(FooFields):
    ...

class FooFields(BaseModel, Bar):
    ...
```

As far as I can tell this is not currently supported.  Is such a thing possible?

**Comment by mat-sop** [comment]
Hey, we don't support it at the moment, but I don't see any objections to adding it.

**Comment by markedwards** [comment]
How do I get it on the roadmap?  Or is it my job to submit the diff?  :-)

**Comment by mat-sop** [comment]
You don't need to link it anywhere else, this issue is enough. And of course, if you want, you can submit pr :)
