### ISSUE TITLE
@mixin directive not stripped from fragments

### ISSUE THREAD

**Issue by markedwards** [mirumee/ariadne-codegen#176]
Mixins inside fragments seem to basically work, but the directive is not stripped from the generated query, leading to errors in the request.

Example:
```GraphQL
fragment FooFields on Foo {
  bar @mixin(from: ".mixins", import: "BarMixin") {
      id
  }
}

query GetFoo {
  getFoo {
    ...FooFields
  }
}
```

The `BarMixin` is correctly inherited in the `GetFooBar` model, but the `@mixin()` is not stripped out.  If I manually remove the directive from the generated code, everything works.

**Comment by mat-sop** [comment]
> The `BarMixin` is correctly inherited in the `GetFooBar` model

`BarMixin` should be added to `FooFieldsBar`, and `GetFooGetFoo ` should inherit `FooFields`. Does this description matches what was generated for this example?

And yes, we should remove `@mixin` from fragments, similar to what we did with operation strings #159

**Comment by markedwards** [comment]
> `BarMixin` should be added to `FooFieldsBar`, and `GetFooGetFoo ` should inherit `FooFields`. Does this description matches what was generated for this example?

Yes, sorry this was a contrived example and I got the naming wrong.  The models all come out as expected, the only issue is with `@mixin()` not being stripped.
