### ISSUE TITLE
Incorrect import with top level fragment with ShorterResultsPlugin

### ISSUE THREAD

**Issue by mat-sop** [mirumee/ariadne-codegen#178]
Let's take example schema and query:
```gql
type Query {
  hello: TypeA!
}

type TypeA {
  valueB: TypeB!
}

type TypeB {
  id: ID!
}
```
```gql
query testQuery {
  ...fragmentHello
}

fragment fragmentHello on Query {
  hello {
    valueB {
      id
    }
  }
}
```

From these we generate `test_query.py`
```py
class TestQuery(FragmentHello):
    pass
```
and `fragments.py`
```py
class FragmentHello(BaseModel):
    hello: "FragmentHelloHello"


class FragmentHelloHello(BaseModel):
    value_b: "FragmentHelloHelloValueB" = Field(alias="valueB")
```

Without `ShorterResultsPlugin` we generate client which looks like this:
```py
from .test_query import TestQuery
...
    async def test_query(self) -> TestQuery:
        ...
        return TestQuery.parse_obj(data)
```

With  `ShorterResultsPlugin`:
```py
from .test_query import FragmentHelloHello, TestQuery
...
    async def test_query(self) -> FragmentHelloHello:
        ...
        return TestQuery.parse_obj(data).hello
```

Problem with client generated with `ShorterResultsPlugin` is that it imports `FragmentHelloHello` from `test_query.py`, but instead it should be imported from `fragments.py`.

**Comment by bombsimon** [comment]
Had a lot to do lately so took me a while to get to this (sorry about that) but it looks like this is an easy fix by just adding all the classes found in the fragments module to the map of imports. Added a similar example to this issue with a test to the PR.
