### ISSUE TITLE
Feature request: Pydantic ^2 support

### ISSUE THREAD

**Issue by pkucmus** [mirumee/ariadne-codegen#194]
FastAPI is on Pydantic 2 since [0.100](https://github.com/tiangolo/fastapi/releases/tag/0.100.0). I'd like to use ariadne-codegen with the newest FastAPI, hence the request :)

**Comment by rafalp** [comment]
This is [already done](https://github.com/mirumee/ariadne-codegen/pull/186) and we plan to ship it sometime next week :)
