### ISSUE TITLE
Feature request: shallow create

### ISSUE THREAD

**Issue by NeedsNoIntroduction** [mirumee/ariadne-codegen#198]
Hey,

we encountered following Problem: 

given two entities "Article" and "Tag", with n-2-n Relationship, we would like to create one entity and attach a list of the other via a list of IDs. 

query_Input would look something like this:
```
  "queryInput": {
    "url": "URL"
    "tags": [
      {
        "id": 1
      },
     ....
    ]
  }
```

Entities (simplified) look like this:
```
entity "Article"  
  id - int  
  url - str  
  tags - [TagEntity]

entity "Tag"
  id - int
  value - str
  articles - [ArticleEntity]
```

Output of codegen is atm. like this: 
```
class ArticleCreateInput(BaseModel):
  id: int
  url: str
  tags: List["TagCreateInput"] = Field(alias="Tags")

class TagCreateInput(BaseModel):
    value: str
```

Problem with the generated code is that we can only create both entities at once (and not just the "primary" entity and attach the other via id's), imho. in this case the ArticleCreateInput should something like this:
```
class ArticleCreateInput(BaseModel):
  id: int
  url: str
  tags: List["TagCreateInput"]  | List["TagInput"] = Field(alias="Tags")
```
TagInput would look like this:
```
class TagInput(BaseModel):
    id: int
```

Is this already achievable out-of-box or maybe a planned feature for next release?

Any help greatly appreciated  :)

Cheers

**Comment by rafalp** [comment]
Hello, extra context why this was closed would be helpful, especially for people who will come to this issue from google searches.
