### ISSUE TITLE
Pydantic Warning Field "model_XXXX" has conflict with protected namespace "model_".

### ISSUE THREAD

**Issue by psylsph** [mirumee/ariadne-codegen#199]
I have some graphql schema that have fields starting with model_ in my current example model_probability, this cause the following warning at runtime:
lib/python3.9/site-packages/pydantic/_internal/_fields.py:127: UserWarning: Field "model_probability" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

the following pydantic webpage (https://docs.pydantic.dev/latest/usage/model_config/#protected-namespaces) seems to suggest that fields beginning with model_ need to be added to an override list or the ConfigDict in the code can have
model_config = ConfigDict(protected_namespaces=())
set, maybe added the protected_namespaces=() to the generated code is the easiest fix.

**Comment by mat-sop** [comment]
Hey, we're already taking care of actual collisions with existing attributes (those that produce exceptions not warnings #196). It looks like you're right, and `protected_namespaces=()` will solve warnings produced by `model_*` fields.
