### ISSUE TITLE
OpenTelemetry support

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne-codegen#200]
Generated client could support opt-in OpenTelemetry spans, to track number and time of made GraphQL calls by application using it.

**Comment by jakub-bacic** [comment]
+1 for that. I'd probably need to add support for Datadog tracing as well. Right now, I'm planning to do that using plugin architecture but I suppose it might be worth adding such solutions to `contrib`.

**Comment by rafalp** [comment]
@jakub-bacic from my understanding [DataDog supports OpenTelemetry for Python](https://docs.datadoghq.com/tracing/trace_collection/otel_instrumentation/), so there's no need for separate "Datadog tracing" implementation.
