### ISSUE TITLE
Example with fully custom type

### ISSUE THREAD

**Issue by psylsph** [mirumee/ariadne-codegen#201]
Has anybody got a more detailed Example with fully custom type, I have a Java Kickstart server that use the Char customer type and I'm trying to implement a client using the generated custom type however whatever I do always end up with a string and the server end rejects it.

**Comment by rafalp** [comment]
What do you mean by fully custom type? Can you share the schema with an example?

**Comment by psylsph** [comment]
I'll try, this is a very simplified version of the schema, char represents the char type from c which does not have an equivalent in Python

scalar Long
scalar Short
scalar Char

schema {
    query: Query
    mutation: Mutation
}

type Query {
  payloads: [Payload!]!

}


type Mutation {
  updateEntityPayload(instance: PayloadInput!): Payload!
}


input PayloadInput {
  payloadBase: Char!
  payloadVariants: [Char!]!
}

type Payload {
  payloadBase: Char!
  payloadVariants: [Char!]!
}

**Comment by psylsph** [comment]
With the following config:

files_to_include = ["api/types/custom_types.py"]
[tool.ariadne-codegen.scalars.Char]
type = ".custom_types.CharScalar"
parse = ".custom_types.parse_char_scalar"
serialize = ".custom_types.serialize_char_scalar"

with the following in the class

class CharScalar:
    
    value: str
    
    def __init__(self, value: str) -> None:
        self.value=value
        
        
def parse_char_scalar(value):
    return CharScalar(value)
    
def serialize_char_scalar(a_char: CharScalar):
    return a_char.value


but this just give me the error
exceptions.GraphQLClientGraphQLMultiError: Variable 'instance' has an invalid value: Expected type 'Char' but was 'String'.

**Comment by psylsph** [comment]
An an pseudo example, I'm basically doing:

with GeneratedSyncClient("http://127.0.0.0:8080/endpoint") as client:
    payloadInput = PayloadInput(payloadBase='N', payLoadVariants="NN")
    client.updateEntityPayload(payloadInput)

the server end point is generated using springboot java-kickstart and the https://github.com/graphql-java/graphql-java-extended-scalars extensions to provide the Char type at that end, I believe it's the server end that is complaining as the ariane client end is not 'wrapping' the value using the manually defined Char type it's almost like the Pydantic is being too cleaver and just working out it's a string as part of the serialize

**Comment by psylsph** [comment]
I worked out my problem the error I was getting was misleading, the issue was the NN
payloadInput = PayloadInput(payloadBase='N', payLoadVariants="NN") should have been
payloadInput = PayloadInput(payloadBase='N', payLoadVariants=["N","N"])
