### ISSUE TITLE
Add full support for skip/include directives

### ISSUE THREAD

**Issue by jakub-bacic** [mirumee/ariadne-codegen#204]
GQL spec defines [skip](https://spec.graphql.org/June2018/#sec--skip) and [include](https://spec.graphql.org/June2018/#sec--include) directives. They are not fully supported cause generated pydantic types cannot parse server-side responses (e.g. skipped part of the query is missing and pydantic raises validation error).

**Example reproduction steps:**
Using https://beta.pokeapi.co/graphql/console/:

```graphql
query getPokemonByName($name: String!, $includeAbilities: Boolean!) {

  pokemon_v2_pokemon(where: {
    name: {
      _eq: $name
    }
  }) {
    id
    name
    pokemon_v2_pokemonabilities @include(if: $includeAbilities) {
      pokemon_v2_ability {
        id
        name
      }
    }
  }

}
```

```
>>> result = client.get_pokemon_by_name('pikachu', include_abilities=False)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jbacic/Documents/Private/ariadne-codegen/app/graphql_client/client.py", line 40, in get_pokemon_by_name
    return GetPokemonByName.model_validate(data)
  File "/Users/jbacic/Documents/Private/ariadne-codegen/.venv/lib/python3.10/site-packages/pydantic/main.py", line 504, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for GetPokemonByName
pokemon_v2_pokemon.0.pokemon_v2_pokemonabilities
  Field required [type=missing, input_value={'id': 25, 'name': 'pikachu'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
```

The following server-side response:
```json
{
  "data": {
    "pokemon_v2_pokemon": [
      {
        "id": 25,
        "name": "pikachu"
      }
    ]
  }
}
```
cannot be parsed by:
```python
class GetPokemonByName(BaseModel):
    pokemon_v2_pokemon: List["GetPokemonByNamePokemonV2Pokemon"]


class GetPokemonByNamePokemonV2Pokemon(BaseModel):
    id: int
    name: str
    pokemon_v2_pokemonabilities: Optional[
        List["GetPokemonByNamePokemonV2PokemonPokemonV2Pokemonabilities"]
    ]
```
because it doesn't contain `pokemon_v2_pokemonabilities` key.

**Comment by jakub-bacic** [comment]
So, I did some experiments and it looks like the codegen recognizes the directive and changes the type of `pokemon_v2_pokemonabilities` to be optional. However, it doesn't assign a default value there so pydantic still fails with "missing required field" validation error.

We could:
1. Assign a default `None` value so it doesn't fail:
```python
class GetPokemonByNamePokemonV2Pokemon(BaseModel):
    id: int
    name: str
    pokemon_v2_pokemonabilities: Optional[
        List["GetPokemonByNamePokemonV2PokemonPokemonV2Pokemonabilities"]
    ] = None
```

2. Change it so it uses `UNSET` instead of `None` to explicitly express the fact the value is actually missing from the response (in this case, the original type won't be converted to optional if it was required before):
```python
class GetPokemonByNamePokemonV2Pokemon(BaseModel):
    id: int
    name: str
    pokemon_v2_pokemonabilities:
        List["GetPokemonByNamePokemonV2PokemonPokemonV2Pokemonabilities"] | UNSET = UNSET
```

Any thoughts or other solution ideas? :)

**Comment by mat-sop** [comment]
You're right, we already set fields to `Optional` for `@skip`/`@include`, and it worked fine with pydantic `1.x.x`. In pydantic v2 `Optional[...]` is not the same as `Optional[...] = None` so it doesn't work when the key is missing. I'm unsure if we should assign `None` or `UNSET` as default to those fields, @rafalp what do you think?

**Comment by jakub-bacic** [comment]
You're right! It was a breaking change from pydantic V1.

I guess in this case, assigning `None` as a default value seems like a proper solution as it will restore the original behavior (before migration to pydantic V2) 🤔.

**Comment by rafalp** [comment]
If Pydantic v1 did `None`, we could go with explicit None too to maintain the old behaviour.
