### ISSUE TITLE
Bug: Union with only one type gets a pydantic error in the generated class

### ISSUE THREAD

**Issue by lyrahalden** [mirumee/ariadne-codegen#209]
First, thanks for the wonderful library. We use ariadne all the time and we love it!

Version of ariadne-codegen: 0.8.0

Simplified example:

Graphql schema:
```
type Incident {
     name
}

  type IncidentEdge {
    "An identifier for an Edge"
    cursor: String!

    "Contains the actual data"
    node: Incident!
  }

  type IncidentsSuccess {
    totalCount: Int!

    "A collection of edges"
    edges: [IncidentEdge!]!
  }

union IncidentResult = IncidentsSuccess

query list_incidents {
  incidents {
    ... on IncidentsSuccess {
      edges {
        node {
              name
        }
      }
    }
 }
}
```
Generated pydantic models:
```
class ListIncidents(BaseModel):
    incidents: Union[
        "ListIncidentsIncidentsIncidentsSuccess",
    ] = Field(discriminator="typename__")


class ListIncidentsIncidentsIncidentsSuccess(BaseModel):
    edges: List["ListIncidentsIncidentsIncidentsSuccessEdges"]


class ListIncidentsIncidentsIncidentsSuccessEdges(BaseModel):
    node: "ListIncidentsIncidentsIncidentsSuccessEdgesNode"


class ListIncidentsIncidentsIncidentsSuccessEdgesNode(BaseModel):
    name: str
```

Error upon application startup:
```
pydantic.errors.PydanticUserError: Model 'ListIncidentsIncidentsIncidentsSuccess' needs a discriminator field for key 'typename__'
For further information visit https://errors.pydantic.dev/2.3/u/discriminator-no-field
```

We tried to solve this error by adding another type to the union and noticed that it did get generated correctly and our application started up without any errors.

Modified graphql schema:
```
type Incident {
     name
}

  type IncidentEdge {
    "An identifier for an Edge"
    cursor: String!

    "Contains the actual data"
    node: Incident!
  }

  type IncidentsSuccess {
    totalCount: Int!

    "A collection of edges"
    edges: [IncidentEdge!]!
  }

  type IncidentNotFound {
    id: Int!
  }
  union IncidentResult = IncidentsSuccess | IncidentNotFound
```
Correctly generated pydantic models:
```
class ListIncidents(BaseModel):
    incidents: Union[
        "ListIncidentsIncidentsIncidentsSuccess",
        "ListIncidentsIncidentsIncidentNotFound",
    ] = Field(discriminator="typename__")


class ListIncidentsIncidentsIncidentsSuccess(BaseModel):
    typename__: Literal["IncidentsSuccess"] = Field(alias="__typename")
    edges: List["ListIncidentsIncidentsIncidentsSuccessEdges"]


class ListIncidentsIncidentsIncidentsSuccessEdges(BaseModel):
    node: "ListIncidentsIncidentsIncidentsSuccessEdgesNode"


class ListIncidentsIncidentsIncidentsSuccessEdgesNode(BaseModel):
    name: str
```
Thanks for your time and let me know if there is any other information I can provide.

**Comment by mat-sop** [comment]
Hey, what's the use case for union with only 1 member? The problem with those is that python's `typing.Union` expects at least 2 members.

**Comment by jakub-bacic** [comment]
I'm also curious what's the use case for that but technically... if that's a valid GQL schema, we might as well try to support it and... map it to a single type instead of creating `typing.Union`? I don't know - I have mixed feeling about that :D

**Comment by lyrahalden** [comment]
@mat-sop @jakub-bacic Thanks for your speedy replies! 

So on the graphql side we have a list-incidents query like this:
```
 incidents(filter: IncidentsFilterInput, sort: IncidentsSortInput, skip: Int, take: Int): IncidentResult!

 union IncidentResult = IncidentsSuccess
```
At this point in our journey, we don't really care about returning an error type or a "not found" type, but we might want to someday. So we're leaving the union type as a stub for ourselves as a reminder that we could return a different type there if we ever needed to.

So, not the most important thing in the world, I guess, but it works for us.

**Comment by mat-sop** [comment]
@jakub-bacic I tested it more carefully and it looks like you're right. `typing.Union` with 1 argument works fine but my IDE gives me an incorrect warning 🤔 

@lyrahalden for now, to work around this, without modifying schema, you can add explicit `__typename` to query, eg:
```gql
query list_incidents {
  incidents {
    ... on IncidentsSuccess {
      __typename
      edges {
        node {
              name
        }
      }
    }
 }
}
```
