### ISSUE TITLE
Feature Request: save remote GQL schema to file

### ISSUE THREAD

**Issue by jakub-bacic** [mirumee/ariadne-codegen#211]
I really like the idea of `remote_schema_url`. However, it has one disadvantage compared to manually fetching the schema and placing it right next to queries directory. In such case, PyCharm (I suppose it should work for other IDEs as well) automatically detects it and provide autocompletion when writing queries.

Based on that, I can see two potential improvement to consider:
- [ ] add new cmd line option to fetch GQL schema so no extra tools are required to do so (Apollo codegen seems to have `fetch-schema` option, see [docs](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#fetch-schema))
- [ ] allow saving schema doc to a file while using `remote_schema_url` (Apollo codegen seems to handle that via `outputPath` in `schemaDownload` configuration, see [docs](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration/#schema-download-configuration))

Those two options are not mutually exclusive so it might make sense to implement both. I'm happy to contribute but I'd like to discuss some details first. What do you think about it? :)

**Comment by mat-sop** [comment]
I like the approach with `fetch-schema` cmd option. We can add this as another strategy, similar to how we handle `graphqlschema`. Here are a few tips regarding implementation:
- we already have a function that takes `remote_schema_url` and returns `graphql.GraphQLSchema` instance - `get_graphql_schema_from_url`
- for converting `graphql.GraphQLSchema` to `str` we can use `graphql.print_ast`

**Comment by jakub-bacic** [comment]
Thanks for the tips! I managed to find the `get_graphql_schema_from_url` earlier myself (I checked how `remote_schema_url` is handled) and wrote a simple script to download the schema based on that. I used `graphql.print_schema` instead of `graphql.print_ast` though (it accepts `GraphQLSchema` object instead of `Node`).

My proposal was to add it as a separate cmd line invocation and simply print the output to stdout (people might save it to file using shell redirection):
```sh
python -m ariadne_codegen fetch-schema ENDPOINT_URL > schema.graphql
```

The real question is what parameters should we accept and whether we should fallback to `pyproject.toml` file for missing values. For example, schema fetching should have an option to add custom headers (and we already have `remote_schema_headers` in toml file). That kinda reminds me of #87.

---
What do you think about keeping it simple for now and just add optional `remote_schema_output_path` to toml config. If it's set, the fetched schema will be additionally saved to the path specified there. We can revisit the idea of adding `fetch-schema` CLI option later, maybe after #87 is done.

**Comment by rafalp** [comment]
I am missing from the `remote_schema_output_path` name something would tell me that using it makes schema stored as SDL file.

**Comment by jakub-bacic** [comment]
> I am missing from the `remote_schema_output_path` name something would tell me that using it makes schema stored as SDL file.

I took the inspiration from Apollo codegen. They additionally provide `outputFormat` parameter where you can choose between JSON and SDL but I don't know if it's required and if not, what's the default value 🤔.

What would you suggest?

**Comment by rafalp** [comment]
We already have `target_file_path` for `graphqlschema`. We could update that one to use different format depending on target files extension: keep current behavior for `.py` but produce SDL string for `*.graphql` and `*.gql` extensions.

**Comment by rafalp** [comment]
Yes, thats correct.

**Comment by jakub-bacic** [comment]
Oh, yeah, it makes sense for `graphqlschema` mode. That would cover the first task I defined ("add option to fetch GQL schema so no extra tools are required to do so") 👍 

What do you think about doing that automatically while generating the client though (second task)? That's my current use case - I'd like to use `client` mode with `remote_schema_url` and at the same time be able to keep the `schema.graphql` file up-to-date (instead of being forced to download it in a separate step).

**Comment by rafalp** [comment]
I am not a fan of args that are doing what other args do in the core. Why cant' this be aliased or otherwise scripted on devs side instead?

**Comment by gnthibault** [comment]
This feature is quite valuable in my opinion any update on Jakub PR ?

**Comment by rafalp** [comment]
I agree it is valuable but a decision on how it should be implemented is needed first.

**Comment by rafalp** [comment]
If you want to save remote schema to the GraphQL file instead of Python file, just change the file extension in the `target_file_path` option to `.graphql`. Eg.:

```
[tool.ariadne-codegen]
remote_schema_url = "https://example.com/graphql/"
target_file_path = "schema.graphql"
```
