### ISSUE TITLE
All Upper case for snake case convert

### ISSUE THREAD

**Issue by davendu** [mirumee/ariadne-codegen#213]
If a query is named `GetBusinessID`, it will be converted to `get_business_i_d`. The better way would be `get_business_id`.

Instead of current implementation in `utils/str_to_snake_case`, I tried to use this regex:

```regex
(?<!^)([A-Z][a-z]|(?<=[a-z])[^a-z]|(?<=[A-Z])[0-9_])(?<!_)
```

But it would also convert from `arg1` to `arg_1`. Though it looks better, this brings lots of breaking in tests. I'm not sure this is a right way since users' code will need many modifications.

Is there any better ways to convert it?

**Comment by mat-sop** [comment]
We expose a plugin hook [`process_name`](https://github.com/mirumee/ariadne-codegen/blob/main/PLUGINS.md#process_name) that can be used to customize generated names for fields, methods, and arguments.
