### ISSUE TITLE
First comment in auto-generated files causes conflicts in git

### ISSUE THREAD

**Issue by szymi-** [mirumee/ariadne-codegen#215]
The first comment in auto-generated files, e.g.: `# Generated by ariadne-codegen on 2023-09-18 16:52`, causes problems when two people auto-generate the same file with different content. Changes that could easily be merged in git without the comment, result in conflicts when the comments are there. Setting `include_comments` to `false` in config is not ideal, as then there is no info for code reviewers etc. that the code in a given file was auto-generated. It should be possible to keep the comments, but without the date (anyway, the approximate date of the change can be found in git).

**Comment by rafalp** [comment]
We could make `include_comments` accept a string value, eg. `"stable"` to make this header comment stable (or deterministic) to avoid silly git conflicts on those.

**Comment by davendu** [comment]
I suggest the header comment in following syntax, so it can have a stable build output as long as meaningful content:

```
# Generated by ariadna-codegen v0.9.0
# Schema path: https://example.com/gql
# Schema checksum: d41d8cd98f00b204e9800998ecf8427e
```
