### ISSUE TITLE
Feature request: Include operationName if available in all requests

### ISSUE THREAD

**Issue by EDjur** [mirumee/ariadne-codegen#225]
Hi!

Currently, only `query` and `variables` (if available) are attached to the request body of any outgoing requests in the base client.

It would make sense to add `operationName` as part of the payload. I know it's part of the `query` when present, but for example [graphql-request attaches it to the body of the outgoing request](https://github.com/jasonkuhrt/graphql-request/blob/main/src/index.ts#L268) ([and here](https://github.com/jasonkuhrt/graphql-request/blob/main/src/index.ts#L589)). And it's good practice to have it easily accessible for e.g. query logs & server side debugging.

In my mind, the implementation would work similarly to how the `variables` is attached currently.

E.g. something like:
```        
if operation_name:
    payload["operationName"] = operation_name
```

Thanks again for this great project! ⭐

**Comment by mat-sop** [comment]
Hi, I was actually thinking about this yesterday 😅 As we already require all operations to have a name, we use it for method and file names. I was thinking of "hardcoding" it in the generated client's method, e.g.
```py
async def create_user(self, user_data: UserCreateInput) -> CreateUser:
    query = gql(
        """
        mutation CreateUser($userData: UserCreateInput!) {
          userCreate(userData: $userData) {
            id
          }
        }
        """
    )
    variables: Dict[str, object] = {"userData": user_data}
    response = await self.execute(query=query, variables=variables, operation_name="CreateUser")
    data = self.get_data(response)
    return CreateUser.model_validate(data)
```

**Comment by EDjur** [comment]
What a coincidence! 

That approach makes a lot of sense I think if it will always be available 👍
