### ISSUE TITLE
Feature request: expose the `gql` query definitions used by the client.

### ISSUE THREAD

**Issue by pkucmus** [mirumee/ariadne-codegen#230]
Having a client like that generated:

```python
class SaleorClient(AsyncBaseClient):
    async def payment_gateway_initialize_session(
        self,
    ) -> AsyncIterator[PaymentGatewayInitializeSession]:
        query = gql(
            """
            subscription PaymentGatewayInitializeSession {
              event {
                __typename
                ...PaymentGatewayInitializeSessionEvent
              }
            }
            """
        )
[...]
```

I would like to access what is under the `query` variable that right now is inside the `payment_gateway_initialize_session` method. I would like to use that definition in my Saleor App manifest. I could not rely on this as the _ws methods are meant for something else, I get that, but as I'm trying to make my app conform to the "ariadne-codegen standard" and I have cut my fragments out of my .graphql query files (to stop the rightful "There can be only one fragment named" complaint) and now I'm left with nothing I could shove into my app manifest.

**Comment by pkucmus** [comment]
In case I'm making no sense, this is what I'm after: I have a partial success with a plugin like this:
```python
import ast

from graphql import ExecutableDefinitionNode
from ariadne_codegen.plugins.base import Plugin


class ExposedGQLDefinitionFunctionPlugin(Plugin):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.stored_operations = {}
        
    def generate_operation_str(
        self, operation_str: str, operation_definition: ExecutableDefinitionNode
    ) -> str:
        self.stored_operations[operation_definition.name.value] = operation_str
        return operation_str

    def generate_client_class(self, class_def: ast.ClassDef) -> ast.ClassDef:
        for name, operation_str in self.stored_operations.items():
            class_def.body.insert(
                0,
                ast.Assign(
                    targets=[
                        ast.Name(
                            id=name,
                            ctx=ast.Store()
                        ),
                    ],
                    value=ast.Constant(value=operation_str)
                )
            )
        
        return ast.fix_missing_locations(class_def)
```

**Comment by mat-sop** [comment]
> In case I'm making no sense, this is what I'm after: I have a partial success with a plugin like this:

What do you mean by partial success? It looks like your plugin exposes operations strings as client class attributes.

**Comment by rafalp** [comment]
We will provide a plugin as part of `contrib` package which will generate `operations.py` module as part of generated client. This module will have definitions for all queries, and `__all__ = ()` declaration so one can easily pull all queries used by client for whatever purpose they have.
