### ISSUE TITLE
Bug: GraphQL spec does not mandate that "data" is always returned

### ISSUE THREAD

**Issue by travigd** [mirumee/ariadne-codegen#240]
This codebase assumes that the `data` key must always be present in the result. This is not the case according to the GraphQL spec: https://spec.graphql.org/October2021/#sec-Response-Format. If a query couldn't be executed (e.g., due to failing authentication on some servers), it will not include a `data` field -- only `errors`.

Consequently, this library doesn't handle that and will instead raise `GraphQlClientInvalidResponseError`.

**Comment by rafalp** [comment]
What is expected behavior if `data` is not present here? Only solution that comes to mind would be setting error response as attribute on `GraphQlClientInvalidResponseError` for people to do whatever makes sense in their project.

**Comment by mat-sop** [comment]
`GraphQlClientInvalidResponseError` already has `response: httpx.Response` attribute https://github.com/mirumee/ariadne-codegen/blob/main/ariadne_codegen/client_generators/dependencies/async_base_client.py#L116

**Comment by rafalp** [comment]
Oh, you are right! Then I don't know what else could we do here.

**Comment by travigd** [comment]
I think ideally raising `GraphQLClientGraphQLMultiError` would be the right™ choice since that's the way this library surfaces anything in the `errors` response. It might require changing the type of `data` there to be `Optional[Dict[str, Any]]`.
