### ISSUE TITLE
Incorrect default value for queries with `@include` directive

### ISSUE THREAD

**Issue by salmannotkhan** [mirumee/ariadne-codegen#272]
First of all, I loved the project. It has everything that anyone can expect.

Recently I ran into an issue, When the field name is in camelCase and uses `@include` directive the generated pydantic code doesn't generate proper default value (`None`)

I have used https://graphqlzero.almansi.me/api schema for testing purpose

`queries.graphql`:
```gql
query foo{
  postData: post (id: 1) @include(if: true)  {
    id
  }
}
```

generated pydantic code:
```py
from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class Foo(BaseModel):
    post_data: Optional["FooPostData"] = Field(alias="postData")


class FooPostData(BaseModel):
    id: Optional[str]
```

`post_data` should be `Field(None, alias="postData")` because it's optional.

**Comment by salmannotkhan** [comment]
Issue seems to be here: https://github.com/mirumee/ariadne-codegen/blob/main/ariadne_codegen/client_generators/result_types.py#L391-L416

We are not assigning positional arg for default or `default` keyword arg. I have fixed it by adding `default` kwarg in there.

**Comment by salmannotkhan** [comment]
I think we should also fix the `generate_pydantic_field` method. It currently only takes keywords arguments. It should accept positional arguments also.

What do you guys think?

**Comment by salmannotkhan** [comment]
@rafalp Can you take a look at this issue? I have already fixed it in local repo, I can create PR for the same.

**Comment by ori-lb** [comment]
Is this issue fixed on master? encountering the same problem.
@salmannotkhan did you raise a pr eventually?

**Comment by salmannotkhan** [comment]
Waiting for @rafalp's permission.

**Comment by bombsimon** [comment]
I don't think you need permission to create a PR. I would suggest just creating it so it can be reviewed when maintainers have the time and while waiting hopefully others will see it and be able to test it or spot things that might require further changes.
