### ISSUE TITLE
Get copy of introspected schema

### ISSUE THREAD

**Issue by rbw** [mirumee/ariadne-codegen#274]
Thanks for an excellent tool!

I'm using the `remote_schema_url` to introspect and generate the Python code, and it works great. However, it would be nice being able to get a copy of the introspected schema as it would aid developing the queries code.

Perhaps I've missed something in the docs and this is already possible. If not, I can create a PR, if you think it makes sense to add this.

**Comment by rafalp** [comment]
This is already supported: https://github.com/mirumee/ariadne-codegen/blob/main/README.md#generating-graphql-schemas-python-representation

**Comment by rbw** [comment]
That generates a Python representation of the schema.
I mean the schema in GraphQL SDL, so I can use that when developing the queries code.

**Comment by rafalp** [comment]
You are wrong, but so is section's header:

> A string with destination path for generated file. Must be either a Python (.py), or GraphQL (.graphql or .gql) file.

If `.graphql` or `.gql` is used, you'll get a copy in SDL.

**Comment by rbw** [comment]
Ah, nice. Thanks!
