### ISSUE TITLE
Field arg named `query` is shadowed by `query` string in generated client methods

### ISSUE THREAD

**Issue by leandrolerena** [mirumee/ariadne-codegen#277]
When using a query as parameter in a graphQL query, it gets overriden by the code generation query field. As a consequence, all graphQL queries which allow for a query parameter do not work. 

I propose to rename your variable to __query (double underscore ) as of the GraphQL Spec (https://spec.graphql.org/October2021/): 

> Any [Name](https://spec.graphql.org/October2021/#Name) within a GraphQL type system must not start with two underscores "__" unless it is part of the [introspection system](https://spec.graphql.org/October2021/#sec-Introspection) as defined by this specification.

I think this would be a safe choice.

See an illustrative example below, where the argument gets directly overridden and as a consequence, the payload has syntax errors

```python
    async def devices(
        self,
        query: Union[Optional[str], UnsetType] = UNSET,
        page: Union[Optional[int], UnsetType] = UNSET,
        page_size: Union[Optional[int], UnsetType] = UNSET,
        id: Union[Optional[str], UnsetType] = UNSET,
        ordering: Union[Optional[str], UnsetType] = UNSET,
        scope: Union[Optional[Any], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Devices:
        query = gql(
            """
            ...
            ...
            ...

```

**Comment by rafalp** [comment]
I understand now. The problem is generated methods shadowing arguments names with internal variables.

**Comment by leandrolerena** [comment]
Yes, precisely! Now to not impose a breaking change (by e.g. introduce an Args Object like other code generators), I think the renaming as described above could be a good option

**Comment by leandrolerena** [comment]
Thanks a lot for your efforts @rafalp and @Minister944. Everything is working as expected! Cheers
