### ISSUE TITLE
How to generate the `queries` file?

### ISSUE THREAD

**Issue by renardeinside** [mirumee/ariadne-codegen#286]
Hey team, 

Thanks a lot for developing the library. 

There is one thing which is quite unclear to me - what if I would like to have a client that can run any possible query? 

Currently, if I understand correctly, the codegen will only cover the queries I've provided in the `queries.graphql` file, is there any way to have all possible queries generated?

**Comment by rafalp** [comment]
> is there any way to have all possible queries generated?

You mean you want to have queries that are products of all possible queries in your schema? Won't it be like millions of those?

**Comment by bombsimon** [comment]
This sounds like the same as #132

**Comment by renardeinside** [comment]
Yes, this is exactly the same thing I'm looking for. I'll close this for now as a duplicate, but in general it seems like the generated API is a bit cumbersome since I cannot programmatically create a query (which would be a convenient option).
