### ISSUE TITLE
[bug] Setting async_client = false does not work properly when enable_custom_operations = true.

### ISSUE THREAD

**Issue by huy-d-nguyen** [mirumee/ariadne-codegen#303]
Hello,

It appears that our recent feature, `enable_custom_operations`, is not functioning correctly when we set `async_client = false`. Although the BaseClient is the synchronous version, the generated client is improperly using async def for its functions (e.g., `async def query` & `async def mutation`) when it should be using normal def.

<img width="781" alt="image" src="https://github.com/user-attachments/assets/f067ec7f-a0ff-40bf-a7ea-fe6867b505ec">

**Comment by DamianCzajkowski** [comment]
Hi,

Yes, I am aware of this issue. In the first iteration, I did not plan to make custom operations compatible with async_client = false. This is not a bug; it is a feature that still needs to be implemented.

Thank you for pointing it out though! If you would like to contribute to this issue, please prepare a pull request for me to review and merge. Thanks!

**Comment by huy-d-nguyen** [comment]
Thank you for your effort, it's much appreciated. Sorry I was too busy to help, but I hope to have a chance to lend a hand in the future.
