### ISSUE TITLE
Support custom scalars

### ISSUE THREAD

**Issue by mat-sop** [mirumee/ariadne-codegen#73]

**Comment by lromanowicz** [comment]
Yes please! Any ETA on adding that? :D @mat-sop

**Comment by rafalp** [comment]
Hello @lromanowicz, we don't have an ETA for this. Currently non-standard scalars are typed as `Any` by codegen and returned in their serialized form.

We are experimenting with both simple approach to scalars where you will define them using a section in `pyproject.toml`:

```
[ariadne-codegen.scalar.datetime]
py_type = "datetime.datetime"
serialize = ".datetime_scalar.serialize"
parse = ".datetime_scalar.parse"
```

And you will just add the `datetime_scalar` to list of files to include in final build.

But we are also considering a plugin system (#67) and letting plugins do the scalars by modifying the generated code, so result types would use Pydantic's magic for scalar's logic.

**Comment by lromanowicz** [comment]
Our API uses Graphene.Date() scalar field and looks like ariadne-codegen might not be able to "see" it as we're getting error like:
`Argument type Date not found in schema`


Other weird behaviour we've found is that it might be creating/appending class names incorrectly (I believe it's result_types):
Example:

```
class GetZendeskToken(BaseModel):
    grantZendeskToken: Optional["GetZendeskTokenGrantZendeskToken"]

class GetZendeskTokenGrantZendeskToken(BaseModel):
    jwtToken: Optional[str]
```

not sure what might be the reason. We don't have these doubled or so in queries/schema files.

**Comment by rafalp** [comment]
Can you create separate issues for those? I rather keep this about dev work for custom plugin support than having that + here's other issues and problems we found with codegen related to scalar handling. :)

**Comment by lromanowicz** [comment]
Sure!
