### ISSUE TITLE
[feature request] configuration option to assign default None value to optional fields in operations functions

### ISSUE THREAD

**Issue by lromanowicz** [mirumee/ariadne-codegen#86]
Hey! 

Would it be possible to add a bool config option like `assign_none_to_optional_params` which would determine wether the client will have default `None` value already assigned to operation`s function parameters?

Let's take an example function:

```
    def some_function(
        self,
        amount: float,
        budget_id: Optional[int],
        memo: Optional[str],
        recipient_id: Optional[int],
        payment_account_id: Optional[str],
        recurring: Optional[bool],
        source_id: int
   )
```

`amount` and `source` are mandatory, rest is optional but obviously it will raise an error that those params were not passed to the function.

We'd love to have an option to already assign these to `None` so we just pass the mandatory fields and eventually any other optional ones.

WDYT? Would it be beneficial (and possible) from your point of view to add such option?

**Comment by rafalp** [comment]
IMHO we should just add `= None` to those in our generator and don't add new configuration knob that will make the API surface for library bigger.

**Comment by lromanowicz** [comment]
That's also great!
