### ISSUE TITLE
Support authorization in schema request from env variable

### ISSUE THREAD

**Issue by antoncyrol** [mirumee/ariadne-codegen#91]
Hello and thanks for this awesome GraphQL client the Python world was missing so far!

We (aim to) use for our internal GraphQL APIs that are protected by an authorization header, just like in the example,
```
remote_schema_headers = {"Authorization" = "Bearer: token"}
```
which works nicely. The issue with this approach is that the token is in the _pyproject.toml_ file that is known to git. Hence, quite some care is required for inserting the token and removing it again before any changes in the _pyproject.toml_ (e.g., other ariadne-codegen settings) are commited. It would be nice if we could point ariadne-codegen to take the credentials (headers) from elsewhere. As the project is using Pydantic, Pydantics BaseSettings might be a good fit. 

At least in our case, the credentials the generated client needs are the same as ariadne-codegen requires for the introspection query. Perhaps, some kind of _globally_ configured headers that are added to all request could make working with ariadne-codegen even more convenient.

**Comment by rafalp** [comment]
We could support specifying env variable as source of authorization token in schema generation.

As for generated client, you can just provide the auth as one of instance arguments.

**Comment by antoncyrol** [comment]
Yes, env variable as source of token would work for us.

**Comment by rafalp** [comment]
I guess we should support settings like `remote_schema_headers = {"Authorization" = $ENV_VAR_NAME}` where env var would store `Bearer: token`
