### ISSUE TITLE
Multiple GraphQL APIs / clients within one app

### ISSUE THREAD

**Issue by antoncyrol** [mirumee/ariadne-codegen#92]
We have an app that needs to gather data from multiple (two) different GraphQL APIs, which is why we would like to generate two separate clients. It would be handy if there was a way to specify multiple clients in the _pyproject.toml_ and the ariadne-codgen command would take an argument that specifies which one shall be generated (if there is more than one configured).

**Comment by rafalp** [comment]
I would rather support multiple configuration files, so you could have `clienta.toml`, `clientb.toml` and direct codegen to either of those through `--config clienta.toml`

**Comment by antoncyrol** [comment]
> I would rather support multiple configuration files, so you could have `clienta.toml`, `clientb.toml` and direct codegen to either of those through `--config clienta.toml`

That's a smart solution and the way to go in my opinion since multiple clients should be the special case.
