### ISSUE TITLE
Fields declared as [String]! are typed as List[str] instead of List[Optional[str]]

### ISSUE THREAD

**Issue by james-seymour-cubiko** [mirumee/ariadne-codegen#99]
hey! Just thought I'd share this bug I stumbled across where non-optional lists of optional scalars (i.e. `[<scalar>]!`) are incorrectly typed as `List[<scalar>]` in the generated pydantic model, instead of `List[Optional[<scalar>]]`

Should be reproducable with the code below:

**schema.graphql**
```
type Query {
  testField: [String]!
}
```
**queries.graphql**
```
query testQuery {
  testField
}
```
generated **graphql_client/test_query.py**
```
# Generated by ariadne-codegen on 2023-03-18 10:22
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel


class TestQuery(BaseModel):
    test_field: List[str] = Field(alias="testField")

TestQuery.update_forward_refs()
```

**Comment by mat-sop** [comment]
Hey! Thank you for creating this issue, it looks like a bug occurs, not only for scalars but for any subtypes.
